kind: Service
apiVersion: v1
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
    component: single
  ports:
  - name: browser
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
