kind: Template
apiVersion: v1
labels:
  application: mavenpop
metadata:
  annotations:
    description: Create a local (hostPath) persistent volume using group id and directory already defined in openshift cluster data resource
  name: mavenpop-neo4j-local-pv

objects:

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: ${PV_NAME}
    annotations:
      pv.beta.kubernetes.io/gid: ${GID}
  spec:
    # storageClassName: local-storage
    persistentVolumeReclaimPolicy: Recycle
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    hostPath:
      path: ${DIR}

parameters:
  - name: GID
    description: Group id used in the underlying data volume in openshift cluster
    required: true
  - name: DIR
    description: path to directory created in openshift cluster
    required: true
  - name: PV_NAME
    description: name of the new persistent volume
    required: true
